name: Docker Image CI

on:

  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-image.yml'

  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-image.yml'


env:
  VERSION: 1.0.2
  IMAGE_NAME: ${{ github.repository }}/licenseware-docker


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Log into github registry
      uses: docker/login-action@v1
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build --tag licenseware-docker --build-arg version=${{ env.VERSION }} .
      
    - name: Stamp Tag and Push image
      if: github.event_name != 'pull_request'
      run: |
        docker tag licenseware-docker ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        docker tag licenseware-docker ghcr.io/${{ env.IMAGE_NAME }}:latest
        docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        docker push ghcr.io/${{ env.IMAGE_NAME }}:latest
